[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
description = "Yet another simple logger implementation for Rust."
edition = "2021"
license-file = "LICENSE"
name = "yaslog"
version = "0.5.1"

[dependencies]
chrono = "0.4"
fern = {version = "0.7", features = ["colored"]}
log = "0.4"
